### ISSUE TITLE
private key

### ISSUE THREAD

**Issue by dqshtwk** [Pymmdrza/Brain33#3]
Why didn't I get any private key?
The application has been running for more than 48 hours, but there are no keys in the found file
How to solve this problem
Thank you for the great effort and wonderful applications on your website

**Comment by Pymmdrza** [comment]
> Why didn't I get any private key? The application has been running for more than 48 hours, but there are no keys in the found file How to solve this problem Thank you for the great effort and wonderful applications on your website

Finding it depends on several different things that are not related to the script's performance. It is better to do some research about this and then use it.
