### ISSUE TITLE
[TXS:-1]

### ISSUE THREAD

**Issue by Pflasta** [Pymmdrza/Brain33#4]
hello i have a litte error 

[MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 Passphrase:abo
[MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 14whsQt8MdQKX4ZidLfJxCgaFJT6yvr61p [TXS:-1]
[MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 16AyFpXDYFdP4dQqQz46n86vXezKW2Qh14 [TXS:-1]
[MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 22334293648899235107853225505770300450935143035691971219652200550697926471787
[MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 3160c321bcd0c49b6755f1e30c7bfdb9a444db2cb3bba2074dfeb9647ded306b
[MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 Passphrase:aboard
[MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 18xjiBxwMTZzAiUaayxrkPDmzptjVC4StD [TXS:-1]
[MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 17L4BCzabKmpF7zYb3gJhysjaL3KXjJbjR [TXS:-1]

can i get a litte bit help to fix this ?

thank you ;)

**Comment by Pymmdrza** [comment]
> hello i have a litte error
> 
> [MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 Passphrase:abo [MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 14whsQt8MdQKX4ZidLfJxCgaFJT6yvr61p [TXS:-1] [MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 16AyFpXDYFdP4dQqQz46n86vXezKW2Qh14 [TXS:-1] [MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 22334293648899235107853225505770300450935143035691971219652200550697926471787 [MMDRZA.COM] ~ SCAN:534 / Found:0 VALUE:0 3160c321bcd0c49b6755f1e30c7bfdb9a444db2cb3bba2074dfeb9647ded306b [MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 Passphrase:aboard [MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 18xjiBxwMTZzAiUaayxrkPDmzptjVC4StD [TXS:-1] [MMDRZA.COM] ~ SCAN:535 / Found:0 VALUE:0 17L4BCzabKmpF7zYb3gJhysjaL3KXjJbjR [TXS:-1]
> 
> can i get a litte bit help to fix this ?
> 
> thank you ;)

Download and use : https://github.com/Pymmdrza/Brain33/releases/tag/v4.3
